---
title: "Lecture 4 Code"
output: html_document
date: "2024-07-10"
---

```{r}
source('../josh-helpers.R')

theme_update(
  axis.text=element_text(size=14),
  axis.title=element_text(size=14)
)

library(patchwork)
```

```{r}
# Make synthetic globe tossing data
set.seed(1)

N_TOSSES = 100

P_WATER = 0.71

MAX_N_LINES = 18

MEAN_TIME_BW_TOSSES = 0.8

SD_TIME_BW_TOSSES = 0.2

# rbinom with size=1 is Bernoulli(p)
# simulated data placeholder
# assume land is 0 and water is 1
is_water = rbinom(N_TOSSES, size=1, p=P_WATER)

# insert real data once collected 
is_water = c(0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1)

# Number of 10 degree longitude lines away from Berkeley
# simulated data placeholder
n_lines = runif(N_TOSSES, min=0, max=MAX_N_LINES)

# insert real data once collected 
n_lines = c(3, 5.5, 8, 13, 1.5, 1, 11, 17, 5, 11, 11, 15, 7, 9, 7, 2, 6.5, 2, 4.5, 8, 15, 12, 0, 9, 6, 8, 9.5, 12, 11, 5, 11, 8.5, 12, 2, 11, 1.5, 15, 2, 1, 11, 8, 14, 7, 3, 0.5, 12, 17, 6, 4, 11, 4.5, 7.5, 6, 12, 4.5)

# Approximate time between globe tosses
# simulated data placeholder
time_bw_tosses = rnorm(
  N_TOSSES, 
  mean = MEAN_TIME_BW_TOSSES, 
  sd = SD_TIME_BW_TOSSES
)

# insert real data once collected 
time_bw_tosses = c(1.5, 1.3, 0.86, 0.98, 1.15, 0.9, 3.04, 1.6, 1.4, 1.1, 1.25, 1.19, 1.3, 0.9, 0.9, 0.29, 0.8, 1.17, 1.3, 1.78, 0.8, 1.16, 1.6, 1.8, 1.08, 0.4, 2.83, 0.94, 1.8, 0.86, 3.4, 1.6, 0.91, 1.54, 1.4, 2.01, 2.8, 1.01, 2.69, 2.9, 1.03, 0.69, 2.3, 1.3, 1.8, 1.18, 2.6, 4, 2.1, 3, 0.5, 1.45, 1.1, 2.1)

MEAN_TIME_BW_TOSSES = mean(time_bw_tosses)
SD_TIME_BW_TOSSES = sd(time_bw_tosses)
```

```{r}
# Expected data distribution of land/water

land_water_prop = tibble(
  type = c('Land', 'Water'),
  prop = c(1 - P_WATER, P_WATER)
)

ggplot(land_water_prop) + 
  geom_col(aes(x=type, y=prop), fill='gray', color='black') +
  geom_text(aes(x=type, y=prop/2, label=scales::percent(prop))) +
  scale_y_continuous(
    name = 'Expected proportion of tosses',
    labels=scales::percent,
    limits=c(0,1)
  ) +
  scale_x_discrete(
    name=NULL
  )
```

```{r}
land_water_prop = tibble(
  type = c('Land', 'Water'),
  prop = c(1 - mean(is_water), mean(is_water))
)

ggplot(land_water_prop) + 
  geom_col(aes(x=type, y=prop), fill='gray', color='black') +
  geom_text(aes(x=type, y=prop/2, label=scales::percent(prop))) +
  scale_y_continuous(
    name = 'Observed proportion of tosses',
    labels=scales::percent,
    limits=c(0,1)
  ) +
  scale_x_discrete(
    name=NULL
  )
```

```{r}
ggplot() +
  geom_histogram(
    aes(x=n_lines, y=..count../sum(..count..)),
    breaks = seq(0, MAX_N_LINES, by=1),
    fill='red', color='black',
    alpha=0.5
  ) +
  scale_x_continuous(
    name='Number of lines from Berkeley',
    breaks=seq(0, MAX_N_LINES, by=3)
  ) +
  scale_y_continuous(
    name='Proportion of tosses',
    labels=scales::percent
  )
```

```{r}
ggplot() +
  geom_histogram(
    aes(x=1:MAX_N_LINES, y=..count../sum(..count..)),
    breaks = seq(0, MAX_N_LINES, by=1),
    fill='gray', color='black'
  ) +
  scale_x_continuous(
    name='Number of lines from Berkeley',
    breaks=seq(0, MAX_N_LINES, by=3)
  ) +
  scale_y_continuous(
    name='Expected proportion of tosses',
    labels=scales::percent
  )
```

```{r}
ggplot() +
  geom_histogram(
    aes(x=time_bw_tosses, y=..count../sum(..count..)),
    fill='gray', color='black',
    alpha=0.5
  ) +
  geom_text(
    aes(x=3, y=0.1, label='Total Height = 1')
  ) +
  scale_y_continuous(
    name = 'Proportion',
    limits=c(0,NA),
    labels=scales::percent
  ) +
  scale_x_continuous(
    name='Seconds between globe tosses',
    # limits=c(0, NA),
    limits=c(-1, 3*MEAN_TIME_BW_TOSSES),
    breaks=seq(-1, 3*MEAN_TIME_BW_TOSSES, 1)
  ) +
  geom_vline(xintercept=0, linetype='dashed')
```
